spring:
  application:
    name: userbase-service
  
  jackson:
    property-naming-strategy: SNAKE_CASE


  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: dummyuser
    password: dummypassword
    driver-class-name: org.postgresql.Driver

  output:
    ansi:
      enabled: ALWAYS



