spring:
  application:
    name: userbase-service

  profiles:
    active: dev

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: dummyuser
    password: dummypassword
    driver-class-name: org.postgresql.Driver

  output:
    ansi:
      enabled: ALWAYS

